<?php
/********************************************************************************

	Total Slider Default Template

	The default template for showing the slides. Used if there is no
	`total-slider-templates/total-slider-template.php` file found in the active
	theme's directory.

	Do not edit this file: copy it into a folder named `total-slider-templates`
	in your theme and make your changes there. The plugin will automatically
	detect its presence.

*********************************************************************************/

/*  Copyright (C) 2011-2012 Peter Upfold.

    This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

/*
Template Options

Crop-Suggested-Width: 600
Crop-Suggested-Height: 300
Disable-XY-Positioning-In-Admin: No
*/
?>
<?php if ($s->slides_count() > 0): ?>
	<ul class="ts-default">

	<?php while ($s->has_slides()): ?>
		<li id="ts-default-slide-<?php $s->the_identifier();?>"
			class="ts-default-slide <?php $s->draggable_parent();?>"
			style="background-image: url('<?php $s->the_background_url();?>');"
		>
			<a href="<?php $s->the_link();?>" class="ts-default-link">
				<div class="ts-default-overlay <?php $s->make_draggable();?>" style="left: <?php $s->the_x();?>px; top: <?php $s->the_y();?>px">
					<h2 class="ts-default-title"><?php $s->the_title();?></h2>
					<div class="ts-default-description">
						<p><?php $s->the_description();?></p>
					</div>
				</div>
			</a>
		</li>
		<?php endwhile ;?>

	</ul>
<?php endif; ?>